name: Ruby
# on: [push, pull_request]
on: [pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ['3.2']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - if: runner.os == 'Linux'
        run: sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - run: bundle install
      - run: git submodule update --init --recursive --depth 1
      - run: gem build ruby2d.gemspec --verbose
      - run: gem install ruby2d-*.gem --local --verbose

      - if: runner.os == 'Linux'
        run: export DISPLAY=:0 && rspec

      - run: rspec
